# Generated by Django 5.1.2 on 2025-01-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0010_osoba_wlasciciel_alter_osoba_nazwisko_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('view_person_other_owner', 'Pozwala zobaczyć modele Osoba innych właścicieli')]},
        ),
    ]
